---
abstract: 'Unpacking of password protected archives for Archive::Zip'
author:
  - 'Matthias Bethke, C<< <matthias at towiski.de> >>'
  - 'Matthias Bethke <matthias@towiski.de>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Archive-Zip-Crypt
no_index:
  directory:
    - inc
    - t
requires:
  Archive::Zip: 1.30
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
